CREATE DATABASE PELUQUERIA_CANINA;
USE PELUQUERIA_CANINA;

CREATE TABLE PERRO
       (ID_PERRO INT(10) PRIMARY KEY,
        NOMBRE VARCHAR(20),
        FECHA_NAC DATE(10),
        SEXO VARCHAR(10),
        DNI_DUEÑO INT(10),
        CONSTRAINT fk_DUEÑO FOREIGN KEY (IdDUEÑO) REFERENCES DUEÑO (Id),
        );

INSERT INTO PERRO VALUES
        (1, 'PERRITO_1','2022-07-01', 'MACHO' , 20258775);

INSERT INTO PERRO VALUES
        (2, 'PERRITO_2','2022-07-14', 'HEMBRA' , 23258795);


CREATE TABLE DUEÑO
       (DNI INT(10) PRIMARY KEY,
        NOMBRE VARCHAR(15),
        APELLIDO VARCHAR(10), 
        TELEFONO INT(14),
        DIRECCION VARCHAR(20) );

INSERT INTO DUEÑO VALUES
        (23584748, 'WALTER','DIAZ', 354255545 , 'CORDOBA');

INSERT INTO DUEÑO VALUES
        (28748275, 'MARIELA','PERALTA', 325485448 , 'MENDOZA')



CREATE TABLE HISTORIAL
       (ID_HISTORIAL INT(10) PRIMARY KEY,
        FECHA DATE(10),
        DESCRIPCION VARCHAR(10), 
        MONTO INT(14),
        PERRO VARCHAR(20) 
        CONSTRAINT fk_PERRO FOREIGN KEY (IdPERRO) REFERENCES PERRO (Id),
        );

INSERT INTO HISTORIAL VALUES
        (1, '2022-07','DESC_1', 100 , '');

INSERT INTO HISTORIAL VALUES
         (2, '2022-07','DESC_2', 100 , '');

SELECT MONTO FROM HISTORIAL
         WHERE FECHA='2022-07';